#!/bin/bash
# =========================================
# Quick Setup | Script Setup Manager
# Edition : Stable Edition V3.1
# Auther  : Geo Project
# (C) Copyright 2024
# =========================================
clear
domain=$(cat /etc/xray/domain)
IP=$( curl -s ifconfig.me )
apt install haproxy -y
 wget -q -O /etc/squid/squid.conf "https://jaka1m.github.io/project/ssh/squid.conf" >/dev/null 2>&1
    wget -O /etc/haproxy/haproxy.cfg "https://jaka1m.github.io/project/xray/haproxy.cfg" >/dev/null 2>&1
    wget -O /etc/nginx/conf.d/xray.conf "https://jaka1m.github.io/project/xray/xray.conf" >/dev/null 2>&1
    sed -i "s/xxx/${domain}/g" /etc/haproxy/haproxy.cfg
    sed -i "s/xxx/${domain}/g" /etc/nginx/conf.d/xray.conf
    sed -i "s/xxx/${IP}/g" /etc/squid/squid.conf
    cat /etc/xray/xray.crt /etc/xray/xray.key | tee /etc/haproxy/hap.pem
    echo ""
