#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	Geo Project
# //	Dscription: Xray Menu Management
# //	email: admin@geolstore.net
# //  telegram: https://t.me/tau_samawa
# //====================================================

# // Root Checking
if [ "${EUID}" -ne 0 ]; then
		echo -e "${EROR} Please Run This Script As Root User !"
		exit 1
fi

# // Export Color & Information
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHT='\033[0;37m'
export NC='\033[0m'
OR='\033[1;93m'
Lred='\e[91m'
LLgreen='\e[92m'
Lyellow='\e[93m'
yellow="\033[1;33m"
green="\e[92;1m"
yellow="\033[1;33m"
cyan="\033[1;36m"

# // Export Banner Status Information
export EROR="[${RED} ERROR ${NC}]"
export INFO="[${YELLOW} INFO ${NC}]"
export OKEY="[${GREEN} OKEY ${NC}]"
export PENDING="[${YELLOW} PENDING ${NC}]"
export SEND="[${YELLOW} SEND ${NC}]"
export RECEIVE="[${YELLOW} RECEIVE ${NC}]"

# // Export Align
export BOLD="\e[1m"
export WARNING="${RED}\e[5m"
export UNDERLINE="\e[4m"

# // Exporting URL Host
source '/etc/geovpn/var.txt'
URL="https://api.telegram.org/bot$INFO_AKUN/sendMessage"
export Server_URLL="raw.githubusercontent.com/jaka1m/perizinan/main"
export Server_Port="443"
export Server_IP="underfined"
export Script_Mode="Stable"
export Auther="geovpn"
MYIP=$(curl -sS ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)
PUB=$(cat /etc/slowdns/server.pub)
NS=$(cat /etc/xray/ns.txt)

# // Exporting IP Address
export IP=$( curl -sS ipinfo.io/ip )

# // Exporting Network Interface
export NETWORK_IFACE="$(ip route show to default | awk '{print $5}')"

# // Validate Result ( 1 )
touch /etc/${Auther}/license.key
export Your_License_Key="$( cat /etc/${Auther}/license.key | awk '{print $1}' )"
export Validated_Your_License_Key_With_Server="$( curl -s https://${Server_URLL}/registered.txt | grep -w $Your_License_Key | head -n1 | cut -d ' ' -f 1 )"
if [[ "$Validated_Your_License_Key_With_Server" == "$Your_License_Key" ]]; then
    validated='true'
else
    echo -e "${EROR} License Key Not Valid"
    exit 1
fi

# // Checking Script Expired
exp=$( curl -s https://${Server_URLL}/registered.txt | grep -w $Your_License_Key | cut -d ' ' -f 4 )
now=`date -d "0 days" +"%Y-%m-%d"`
expired_date=$(date -d "$exp" +%s)
now_date=$(date -d "$now" +%s)
sisa_hari=$(( ($expired_date - $now_date) / 86400 ))
if [[ $sisa_hari -lt 0 ]]; then
    echo $sisa_hari > /etc/${Auther}/license-remaining-active-days.db
    echo -e "${EROR} Your License Key Expired ( $sisa_hari Days )"
    exit 1
else
    echo $sisa_hari > /etc/${Auther}/license-remaining-active-days.db
fi
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
  clear
  echo -e "  ${OR}──────────────────────────────────────${NC}"
  printf "\e[1;92m     ⚜⚜\e[0m\e[1;77m Add SSH OVPN Account \e[1;92m⚜⚜\e[0m\n"
  echo -e "  ${OR}──────────────────────────────────────${NC}"
  echo ""
  read -rp "  Input Username: " -e user
  CLIENT_EXISTS=$(grep -w $user /etc/ssh/.ssh.db | wc -l)

  if [[ ${CLIENT_EXISTS} == '1' ]]; then
    clear
    echo -e "  ${OR}──────────────────────────────────────${NC}"
    printf "\e[1;92m     ⚜⚜\e[0m\e[1;77m Add SSH OVPN Account \e[1;92m⚜⚜\e[0m\n"
    echo -e "  ${OR}──────────────────────────────────────${NC}"
    echo ""
    echo "       The customer name already exists"
    echo ""
    echo -e "  ${OR}───────────────────────────────────────${NC}"
    exit

  fi
done

sec=1
spinner=(⣻ ⢿ ⡿ ⣟ ⣯ ⣷)
while [ $sec -gt 0 ]; do
  echo -ne "\e[33m ${spinner[sec]} Setting up a Premium Account $sec seconds...\r"
  sleep 1
  sec=$(($sec - 1))
done
clear
echo ""
echo -e "\e[1;32m     input dependecies account $user\e[0m\n"
echo -e "\033[0;33m ⚜⚜  Script by Geo Project  ⚜⚜\e[0m\n"
echo ""
echo "    No unlimited for limit ssh ovpn"
echo "          at least with 1 ip"
echo ""
echo "   Username : $user"
until [[ $PASSWD =~ ^[a-zA-Z0-9]+$ ]]; do
  read -p "   Password : " PASSWD
done
until [[ $EXPIRED =~ ^[0-9]+$ ]]; do
  read -p "   Expired (days): " EXPIRED
done
until [[ $iplim =~ ^[0-9]+$ ]]; do
  read -p "   Limit User (IP): " iplim
done

IP=$(curl -sS ifconfig.me)
domain=$(cat /etc/xray/domain)
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl $bln, $thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2 $bln2, $thn2"
useradd -e $(date -d "$EXPIRED days" +"%Y-%m-%d") -s /bin/false -M $user
exp="$(chage -l $user | grep "Account expires" | awk -F": " '{print $2}')"
dbexp=$(date -d "$EXPIRED days" +"%Y-%m-%d")
echo -e "$PASSWD\n$PASSWD\n" | passwd $user &>/dev/null

if [[ ${c} != "0" ]]; then
  echo "${iplim}" >/etc/ssh/${user}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/ssh/.ssh.db
fi
echo "### ${user} ${dbexp}" >>/etc/ssh/.ssh.db

cat >/var/www/html/ssh-$user.txt <<END

---------------------
Format SSH OVPN Account
---------------------
Username         : $user
Password         : $PASSWD
---------------------
Host XrayDNS : ${NS}
Pub Key          : ${PUB}
IP               : $IP
Host             : $domain
Port OpenSSH     : 443, 80, 22
Port UdpSSH      : 1-65535
Port Dropbear    : 443, 109
Port Dropbear WS : 443, 109
Port SSH WS      : 80, 8080
Port SSH SSL WS  : 443
Port SSL/TLS     : 443
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 443, 1194
Port OVPN UDP    : 2200
BadVPN UDP       : 7100, 7300, 7300
---------------------
Payload WSS: GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf] 
---------------------
OpenVPN Link     : http://$domain:81
---------------------
Aktif Selama         : $EXPIRED Hari
Dibuat Pada          : $tnggl
Berakhir Pada        : $exp

END

TEXT="
<code>====================</code>
<code>SSH OVPN Account     </code>
<code>====================</code>
<code>Username         : </code> <code>$user</code>
<code>Password         : </code> <code>$PASSWD</code>
<code>====================</code>
<code>Host XrayDNS : </code> <code>${NS}</code>
<code>Pub Key          : </code> <code>${PUB}</code>
<code>IP               : $IP</code>
<code>Host             : </code> <code>$domain</code>
<code>Port OpenSSH     : 443, 80, 22</code>
<code>Port Dropbear    : 443, 109</code>
<code>Port SSH WS      : 80, 8080 </code>
<code>Port SSH UDP     : 1-65535 </code>
<code>Port SSH SSL WS  : 443</code>
<code>Port SSL/TLS     : 443</code>
<code>Port OVPN WS SSL : 443</code>
<code>Port OVPN SSL    : 443</code>
<code>Port OVPN TCP    : 443, 1194</code>
<code>Port OVPN UDP    : 2200</code>
<code>BadVPN UDP       : 7100, 7300, 7300</code>
<code>====================</code>
<code>Payload WSS      : </code><code>GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]</code>
<code>====================</code>
OVPN Download : https://$domain:81/
<code>====================</code>
<code>Save Link Account: </code>https://$domain:81/ssh-$user.txt
<code>====================</code>
Aktif Selama         : $EXPIRED Hari
Dibuat Pada          : $tnggl
Berakhir Pada        : $exp
<code>====================</code>
"

curl -s --max-time $TIME -d "chat_id=$ADMIN&disable_web_page_preview=1&text=$TEXT&parse_mode=html" $URL >/dev/null
echo ""
clear
echo -e "
\033[0;34m====================\033[0m
\e[92;1m  SSH OVPN Account     \E[0m
\033[0;34m====================\033[0m
Username         : $user
Password         : $PASSWD
\033[0;34m====================\033[0m
IP               : $IP
Host             : $domain
Port OpenSSH     : 443, 80, 22
Port UdpSSH      : 1-65535
Port Dropbear    : 443, 109
Port Dropbear WS : 443, 109
Port SSH WS      : 80, 8080
Port SSH SSL WS  : 443
Port SSL/TLS     : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 443, 1194
Proxy Squid      : 8000
Port OVPN UDP    : 2200
BadVPN UDP       : 7100, 7300, 7300
Host XrayDNS : ${NS}
Pub Key          : ${PUB}
\033[0;34m====================\033[0m
Payload WSS      : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]
\033[0;34m====================\033[0m
OpenVPN Link     : https://$domain:81
\033[0;34m====================\033[0m
Save Link Account: https://$domain:81/ssh-$user.txt
\033[0;34m====================\033[0m
Aktif Selama   : $EXPIRED Hari
Dibuat Pada    : $tnggl
Berakhir Pada  : $exp
\033[0;34m====================\033[0m
" | tee -a /etc/xray/log-createssh-${user}.log
echo ""
read -n 1 -s -r -p "Press any key to back on menu"
m-sshws
