#!/bin/bash
clear

domain=$(cat /etc/xray/domain)
PUB=$(cat /etc/slowdns/server.pub)
CITY=$(cat /etc/xray/city)
NS=$(cat /etc/xray/dns)
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
  clear
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${putih}${BGX}                     ADD TROJAN ACCOUNT                ${NC}"
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${putih}"
read -p "   Username         : " user
read -p "   Expired (days)   : " masaaktif
read -p "   Limit User (GB)  : " Quota
read -p "   Limit User (IP): " iplim
read -p "   Bug Host (BUG): " bug
echo -e "${NC}"
  CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

  if [[ ${CLIENT_EXISTS} == '1' ]]; then
    clear
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${putih}${BGX}                     ADD TROJAN ACCOUNT                      ${NC}"
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
    echo -e "${putih}   A client with the specified name was already created, please choose another name. ${NC}"
    echo -e ""
    echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    read -n 1 -s -r -p "   Press [ Enter ] to back menu trojan"
    trojan
  fi
done
max=2
#cat >/usr/local/sbin/uuid <<EOF
#geo-project-anak-sumbawa
#EOF
#uuid=$(cat /usr/local/sbin/uuid)
uuid=$(cat /proc/sys/kernel/random/uuid)
echo ""
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl-$bln-$thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2-$bln2-$thn2"
exp=`date -d "$masaaktif days" +"%d-%b-%Y"`
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
cat >/var/www/html/trojan-$user.txt <<-END

---------------------
# Format Trojan GO/WS (CDN)
---------------------

- name: Trojan-$user-GO/WS (CDN)
  server: ${domain}
  port: 443
  type: trojan
  password: ${uuid}
  network: ws
  sni: ${domain}
  skip-cert-verify: true
  udp: true
  ws-opts:
    path: /trojan-ws
    headers:
        Host: ${domain}
---------------------
# Format Trojan gRPC
---------------------

- name: Trojan-$user-gRPC (SNI)
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-grpc

---------------------
 Link Trojan Account
---------------------
Link WS TLS : trojan://${uuid}@${domain}:443?path=%2Fwhatever%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#Trojan-$user-GO%2BWS
---------------------
Link WS NTLS : trojan://${uuid}@${BUG}:80?path=/trojan-ws&security=none&host=${domain}&type=ws&sni=${domain}#Trojan-$user-NON%2BWS"
---------------------
Link GRPC : trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#Trojan-$user-GRPC
---------------------

END
trojanlink="trojan://${uuid}@${domain}:443?path=%2Fwhatever%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#Trojan-$user-GO%2BWS"
trojanlink1="trojan://${uuid}@${bug}:80?path=/trojan-ws&security=none&host=${domain}&type=ws&sni=${domain}#Trojan-$user-NON%2BWS"
trojanlink2="trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#Trojan-$user-GRPC"

systemctl restart xray
systemctl restart nginx
service cron restart
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi
if [ -z ${iplim} ]; then
  iplim="0"
fi
if [ -z ${Quota} ]; then
  Quota="0"
fi
c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))
if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
  echo "${iplim}" >/etc/trojan/${user}IP
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
fi
echo "### ${user} ${exp} ${Quota} ${iplim} ${uuid}" >>/etc/trojan/.trojan.db
clear
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e " \e[1;97;101m            SUCCES CREAT TROJAN ACCOUNT               \e[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "Remarks        : ${user}" | tee -a /etc/xray/log-create-${user}.log
echo -e "Host           : ${domain}" | tee -a /etc/xray/log-create-${user}.log
echo -e "User Quota     : ${Quota} GB" | tee -a /etc/xray/log-create-${user}.log
echo -e "Port WS(TLS)   : 443" | tee -a /etc/xray/log-create-${user}.log
echo -e "Port  gRPC     : 443" | tee -a /etc/xray/log-create-${user}.log
echo -e "User ID        : ${uuid}" | tee -a /etc/xray/log-create-${user}.log
echo -e "AlterID        : 0" | tee -a /etc/xray/log-create-${user}.log
echo -e "Security       : auto" | tee -a /etc/xray/log-create-${user}.log
echo -e "Path           : /trojan" | tee -a /etc/xray/log-create-${user}.log
echo -e "Network        : WS(TLS) or gRPC" | tee -a /etc/xray/log-create-${user}.log
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "Link WS   : ${trojanlink}" | tee -a /etc/xray/log-create-${user}.log | tee -a /etc/xray/log-create-${user}.log
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "Link GRPC : ${trojanlink1}" | tee -a /etc/xray/log-create-${user}.log
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "Link GRPC : ${trojanlink2}" | tee -a /etc/xray/log-create-${user}.log
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "Format OpenClash : https://${domain}:81/trojan-$user.txt" | tee -a /etc/xray/log-create-${user}.log
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "Expired On : $exp" | tee -a /etc/xray/log-create-${user}.log
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "" | tee -a /etc/xray/log-create-${user}.log
