#!/bin/bash
NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vmess/.vmess.db")
if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    echo ""
    echo "   You have no existing clients!"
    echo ""
    exit 0
fi
listmem=$(grep -s "^### " "/etc/vmess/.vmess.db" | cut -d ' ' -f 2-3 | column -t | sort | uniq)
#echo "Member Xray/vmess"
echo "**═══════════════**"
echo "**USERNAME EXPIRED**"
echo "**═══════════════**"
echo "$listmem"
exit