#!/bin/bash

MYIP=$(curl -sS ipv4.icanhazip.com);
echo "Checking VPS"

NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/ssh/.ssh.db")
if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
    echo ""
    echo "  No customer name available"
    echo ""
    exit 0
fi
echo ""
echo "     NO  USERNAME     EXPIRED"
echo -e "  ${cyan}==============================${NC}"
grep -E "^### " "/etc/ssh/.ssh.db" | cut -d ' ' -f 2-3 | column -t | nl -s ') '
until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
    if [[ ${CLIENT_NUMBER} == '1' ]]; then
        read -rp "Select one client [1]: " CLIENT_NUMBER
    else
        echo ""
        until [[ $CLIENT_NUMBER =~ ^[0-9]+$ ]]; do
            read -rp "     Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
        done
        user=$(grep -E "^### " "/etc/ssh/.ssh.db" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
        exp=$(grep -E "^### " "/etc/ssh/.ssh.db" | cut -d ' ' -f 3 | sed -n "${CLIENT_NUMBER}"p)
        userdel -f $user
        sed -i "/^### $user/d" /etc/ssh/.ssh.db
        rm /etc/xray/log-createssh-$user.log
        rm /var/www/html/ssh-$user.txt
        clear
        echo -e "  ${cyan}=======================================${NC}"
        echo -e "Delete ssh ovpn Account User ${green}$user${NC} Successfully"
        echo -e "account has been permanently deleted"
        echo -e "  ${cyan}=======================================${NC}"
        echo ""
        
    fi
done
echo ""