#!/bin/bash
if [ -e "/var/log/auth.log" ]; then
    LOG="/var/log/auth.log"
fi
if [ -e "/var/log/secure" ]; then
    LOG="/var/log/secure"
fi
echo " OpenSSH user login "
echo "═══════════════"
echo "𝙸𝙳 | 𝚄𝚜𝚎𝚛𝚗𝚊𝚖𝚎 | 𝙸𝙿 𝙰𝚍𝚍𝚛𝚎𝚜𝚜"
cat $LOG | grep -i sshd | grep -i "Accepted password for" >/tmp/login-db.txt
data=($(ps aux | grep "\[priv\]" | sort -k 72 | awk '{print $2}'))
for PID in "${data[@]}"; do
    cat /tmp/login-db.txt | grep "sshd\[$PID\]" >/tmp/login-db-pid.txt
    NUM=$(cat /tmp/login-db-pid.txt | wc -l)
    USER=$(cat /tmp/login-db-pid.txt | awk '{print $9}')
    IP=$(cat /tmp/login-db-pid.txt | awk '{print $11}')
    if [ $NUM -eq 1 ]; then
        echo "$PID - $USER - $IP"
    fi
done
echo ""
data=($(ps aux | grep -i dropbear | awk '{print $2}'))
echo " Dropbear user login "
echo "═══════════════"
echo "𝙸𝙳 | 𝚄𝚜𝚎𝚛𝚗𝚊𝚖𝚎 | 𝙸𝙿 𝙰𝚍𝚍𝚛𝚎𝚜𝚜"
cat $LOG | grep -i dropbear | grep -i "Password auth succeeded" >/tmp/login-db.txt
for PID in "${data[@]}"; do
    cat /tmp/login-db.txt | grep "dropbear\[$PID\]" >/tmp/login-db-pid.txt
    NUM=$(cat /tmp/login-db-pid.txt | wc -l)
    USER=$(cat /tmp/login-db-pid.txt | awk '{print $10}')
    IP=$(cat /tmp/login-db-pid.txt | awk '{print $12}')
    if [ $NUM -eq 1 ]; then
        echo "$PID - $USER - $IP"
    fi
done
