#!/bin/bash
# COLOR VALIDATION

RED='\033[0;31m'
NC='\033[0m'
gray="\e[1;30m"
Blue="\033[36m"
GREEN='\033[0;32m'
grenbo="\e[92;1m"
yellow='\033[0;33m'
ISP=$(cat /etc/xray/isp)
CITY=$(cat /etc/xray/city)
domain=$(cat /etc/xray/domain)
WKT=$(curl -s ipinfo.io/timezone)
IPVPS=$(curl -s ipv4.icanhazip.com)
uptime="$(uptime -p | cut -d " " -f 2-10)"
RAM=$(free -m | awk 'NR==2 {print $2}')
USAGERAM=$(free -m | awk 'NR==2 {print $3}')
MEMOFREE=$(printf '%-1s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
LOADCPU=$(printf '%-0.00001s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
MODEL=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
CORE=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
DATEVPS=$(date +'%d/%m/%Y')
TIMEZONE=$(printf '%(%H:%M:%S)T')
SERONLINE=$(uptime -p | cut -d " " -f 2-10000)
tram=$(free -m | awk 'NR==2 {print $2}')
swap=$(free -m | awk 'NR==4 {print $2}')
freq=$(awk -F: ' /cpu MHz/ {freq=$2} END {print freq}' /proc/cpuinfo)
cores=$(awk -F: '/model name/ {core++} END {print core}' /proc/cpuinfo)
cname=$(awk -F: '/model name/ {name=$2} END {print name}' /proc/cpuinfo)
Open_SSH=$(systemctl status ssh | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Dropbear=$(systemctl status dropbear | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Dropbear_Websocket=$(systemctl status dropbear | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
SSH_Websocket=$(systemctl status ws | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
OpenVPN=$(systemctl status openvpn | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Nginx_Webserver=$(systemctl status nginx | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Haproxy=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
DNS_Server=$(systemctl status server | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
DNS_Client=$(systemctl status client | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
OpenVPN_Websocket=$(systemctl status ws | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
XRAY_Vmess_TLS=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
XRAY_Vmess_gRPC=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
XRAY_Vmess_None_TLS=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
XRAY_Vless_TLS=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
XRAY_Vless_gRPC=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
XRAY_Vless_None_TLS=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Trojan_gRPC=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Trojan_WS=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Shadowsocks_WS=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Shadowsocks_gRPC=$(systemctl status haproxy | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Iptables=$(systemctl status netfilter-persistent | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Squid=$(systemctl status squid | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
BadVPN=$(systemctl status udp-mini-1 | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
RClocal=$(systemctl status rc-local | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
Autorebot=$(systemctl status rc-local | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
OSSSS=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')
if [[ $Open_SSH == "running" ]]; then
    status_1="🟢 ON"
else
    status_1="🔴 OFF"
fi

if [[ $Dropbear == "running" ]]; then
    status_2="🟢 ON"
else
    status_2="🔴 OFF"
fi

if [[ $Dropbear_Websocket == "running" ]]; then
    status_3="🟢 ON"
else
    status_3="🔴 OFF"
fi

if [[ $SSH_Websocket == "running" ]]; then
    status_4="🟢 ON"
else
    status_4="🔴 OFF"
fi

if [[ $OpenVPN == "exited" ]]; then
    status_5="🟢 ON"
else
    status_5="🔴 OFF"
fi

if [[ $Nginx_Webserver == "running" ]]; then
    status_6="🟢 ON"
else
    status_6="🔴 OFF"
fi

if [[ $Haproxy == "running" ]]; then
    status_7="🟢 ON"
else
    status_7="🔴 OFF"
fi

if [[ $DNS_Server == "running" ]]; then
    status_8="🟢 ON"
else
    status_8="🔴 OFF"
fi

if [[ $DNS_Client == "running" ]]; then
    status_9="🟢 ON"
else
    status_9="🔴 OFF"
fi

if [[ $OpenVPN_Websocket == "running" ]]; then
    status_10="🟢 ON"
else
    status_10="🔴 OFF"
fi

if [[ $XRAY_Vmess_TLS == "running" ]]; then
    status_11="🟢 ON"
else
    status_11="🔴 OFF"
fi

if [[ $XRAY_Vmess_gRPC == "running" ]]; then
    status_12="🟢 ON"
else
    status_12="🔴 OFF"
fi

if [[ $XRAY_Vmess_None_TLS == "running" ]]; then
    status_13="🟢 ON"
else
    status_13="🔴 OFF"
fi

if [[ $XRAY_Vless_TLS == "running" ]]; then
    status_14="🟢 ON"
else
    status_14="🔴 OFF"
fi

if [[ $XRAY_Vless_gRPC == "running" ]]; then
    status_15="🟢 ON"
else
    status_15="🔴 OFF"
fi

if [[ $XRAY_Vless_None_TLS == "running" ]]; then
    status_16="🟢 ON"
else
    status_16="🔴 OFF"
fi

if [[ $Trojan_gRPC == "running" ]]; then
    status_17="🟢 ON"
else
    status_17="🔴 OFF"
fi

if [[ $Trojan_WS == "running" ]]; then
    status_18="🟢 ON"
else
    status_18="🔴 OFF"
fi

if [[ $Shadowsocks_WS == "running" ]]; then
    status_19="🟢 ON"
else
    status_19="🔴 OFF"
fi

if [[ $Shadowsocks_gRPC == "running" ]]; then
    status_20="🟢 ON"
else
    status_20="🔴 OFF"
fi

if [[ $Iptables == "exited" ]]; then
    status_21="🟢 ON"
else
    status_21="🔴 OFF"
fi

if [[ $Squid == "running" ]]; then
    status_22="🟢 ON"
else
    status_22="🔴 OFF"
fi

if [[ $BadVPN == "running" ]]; then
    status_23="🟢 ON"
else
    status_23="🔴 OFF"
fi

if [[ $RClocal == "exited" ]]; then
    status_24="🟢 ON"
else
    status_24="🔴 OFF"
fi

if [[ $Autorebot == "exited" ]]; then
    status_25="🟢 ON"
else
    status_25="🔴 OFF"
fi
printf "
◇━━━━━━━━━━━━━◇
❖ Service Info ❖
◇━━━━━━━━━━━━━◇
Uptime = $(uptime -p|cut -d " " -f 2-10000)
WKT    = $(curl -s ipinfo.io/timezone)
Time   = $TIMEZONE
OS     = ${MODEL}
ISP    = $(cat /etc/xray/isp)
CITY   = $(cat /etc/xray/city)
RAM    = ${RAM} MB / ${USAGERAM} MB 
Domain = ${domain}
IPVPS  = ${IPVPS}
◇━━━━━━━━━━━━━◇
Open_SSH        : $status_1
Dropbear        : $status_2
Dropbear_WS     : $status_3
SSH_Websocket   : $status_4
OpenVPN         : $status_5
Nginx_Webserver : $status_6
Haproxy         : $status_7
DNS_Server      : $status_8
DNS_Client      : $status_9
OpenVPN_WS      : $status_10
Xray_Vmess_TLS  : $status_11
Xray_Vmess_gRPC : $status_12
Xray_Vmess_NTLS : $status_13
Xray_Vless_TLS  : $status_14
Xray_Vless_gRPC : $status_15
Xray_Vless_NTLS : $status_16
Trojan_gRPC     : $status_17
Trojan_WS       : $status_18
Shadowsocks_WS  : $status_19
Shadowsocks_gRPC: $status_20
Iptables        : $status_21
Squid           : $status_22
BadVPN          : $status_23
RClocal         : $status_24
Autoreboot      : $status_25

@tau_samawa
◇━━━━━━━━━━━━━◇"
