#!/bin/bash
RED='\033[0;31m'
NC='\e[0m'
gray="\e[1;30m"
blue="\e[1;96m"
putih="\e[1;97m"
putih1="\e[97m"
green='\033[0;32m'
grenbo="\033[1;95m"
YELL='\033[1;33m'
BGX="\e[104m"
clear
domain=$(cat /etc/xray/domain)
PUB=$(cat /etc/slowdns/server.pub)
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
  clear
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${putih}${BGX}                     ADD VMESS ACCOUNT                ${NC}"
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${putih}"
read -p "   Username         : " user
read -p "   Expired (days)   : " masaaktif
read -p "   Limit User (GB)  : " Quota
read -p "   Limit User (IP): " iplim
echo -e "${NC}"
  CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

  if [[ ${CLIENT_EXISTS} == '1' ]]; then
    clear
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${putih}${BGX}                     ADD VMESS ACCOUNT                      ${NC}"
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
    echo -e "${putih}   A client with the specified name was already created, please choose another name. ${NC}"
    echo -e ""
    echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    read -n 1 -s -r -p "   Press [ Enter ] to back menu vmess"
    vmess
  fi
done
max=2
#cat >/usr/local/sbin/uuid <<EOF
#geo-project-anak-sumbawa
#EOF
#uuid=$(cat /usr/local/sbin/uuid)
uuid=$(cat /proc/sys/kernel/random/uuid)
echo ""
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl-$bln-$thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2-$bln2-$thn2"
exp=`date -d "$masaaktif days" +"%d-%b-%Y"`
sed -i '/#vmess$/a\### '"$user $expe"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
exp=$(date -d "$masaaktif days" +"%d-%b-%Y")
sed -i '/#vmessgrpc$/a\### '"$user $expe"'\
},{"id": "'""$uuid""'","alterId": '"0"',"email": "'""$user""'"' /etc/xray/config.json
cat >/etc/xray/$user-tls.json <<EOF
      {
      "v": "2",
      "ps": "$user WS (CDN) TLS",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF
cat >/etc/xray/$user-non.json <<EOF
      {
      "v": "2",
      "ps": "$user WS (CDN) NTLS",
      "add": "${domain}",
      "port": "80",
      "id": "${uuid}",
      "aid": "0",
      "net": "ws",
      "path": "/vmess",
      "type": "none",
      "host": "${domain}",
      "tls": "none"
}
EOF
cat >/etc/xray/$user-grpc.json <<EOF
      {
      "v": "2",
      "ps": "$user (SNI) GRPC",
      "add": "${domain}",
      "port": "443",
      "id": "${uuid}",
      "aid": "0",
      "net": "grpc",
      "path": "vmess-grpc",
      "type": "none",
      "host": "${domain}",
      "tls": "tls"
}
EOF
cat >/var/www/html/vmess-$user.txt <<-END

---------------------
# Format Vmess WS (CDN)
---------------------

- name: Vmess-$user-WS (CDN)
  type: vmess
  server: ${domain}
  port: 443
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: ${domain}
---------------------
# Format Vmess WS (CDN) Non TLS
---------------------

- name: Vmess-$user-WS (CDN) Non TLS
  type: vmess
  server: ${domain}
  port: 80
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  udp: true
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vmess
    headers:
      Host: ${domain}
---------------------
# Format Vmess gRPC (SNI)
---------------------

- name: Vmess-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vmess
  uuid: ${uuid}
  alterId: 0
  cipher: auto
  network: grpc
  tls: true
  servername: ${domain}
  skip-cert-verify: true
  grpc-opts:
    grpc-service-name: vmess-grpc

---------------------
# Link Vmess Account
---------------------
Link TLS : vmess://$(base64 -w 0 /etc/xray/$user-tls.json)
---------------------
Link none TLS : vmess://$(base64 -w 0 /etc/xray/$user-non.json)
---------------------
Link GRPC : vmess://$(base64 -w 0 /etc/xray/$user-grpc.json)
---------------------

END
vmesslink1="vmess://$(base64 -w 0 /etc/xray/$user-tls.json)"
vmesslink2="vmess://$(base64 -w 0 /etc/xray/$user-non.json)"
vmesslink3="vmess://$(base64 -w 0 /etc/xray/$user-grpc.json)"

systemctl restart xray
systemctl restart nginx

service cron restart
if [ ! -e /etc/vmess ]; then
  mkdir -p /etc/vmess
fi
if [ -z ${iplim} ]; then
  iplim="0"
fi
if [ -z ${Quota} ]; then
  Quota="0"
fi
c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))
if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vmess/${user}
  echo "${iplim}" >/etc/vmess/${user}IP
fi
DATADB=$(cat /etc/vmess/.vmess.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vmess/.vmess.db
fi
echo "### ${user} ${exp} ${Quota} ${iplim} ${uuid}" >>/etc/vmess/.vmess.db
clear
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "${putih}${BGX}                SUCCESS CREATE  VMESS                 ${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "Remarks      : ${user}" | tee -a /etc/xray/log-create-${user}.log
echo -e "Domain       : ${domain}" | tee -a /etc/xray/log-create-${user}.log
echo -e "User Quota   : ${Quota} GB" | tee -a /etc/xray/log-create-${user}.log
echo -e "Port TLS     : 443" | tee -a /etc/xray/log-create-${user}.log
echo -e "Port NTLS    : 80, 8080" | tee -a /etc/xray/log-create-${user}.log
echo -e "Port DNS     : 443, 53 " | tee -a /etc/xray/log-create-${user}.log
echo -e "Port GRPC    : 443" | tee -a /etc/xray/log-create-${user}.log
echo -e "User ID      : ${uuid}" | tee -a /etc/xray/log-create-${user}.log
echo -e "AlterId      : 0" | tee -a /etc/xray/log-create-${user}.log
echo -e "Security     : auto" | tee -a /etc/xray/log-create-${user}.log
echo -e "Network      : WS or gRPC" | tee -a /etc/xray/log-create-${user}.log
echo -e "Path TLS     : /vmess - /multipath" | tee -a /etc/xray/log-create-${user}.log
echo -e "Path Dynamic : CF-XRAY:http://bug.com " | tee -a /etc/xray/log-create-${user}.log
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "                      LINK WS TLS" | tee -a /etc/xray/log-create-${user}.log
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "     ${vmesslink1}" | tee -a /etc/xray/log-create-${user}.log
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "                    LINK WS NONE TLS" | tee -a /etc/xray/log-create-${user}.log
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "     ${vmesslink2}" | tee -a /etc/xray/log-create-${user}.log
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "                        LINK GRPC" | tee -a /etc/xray/log-create-${user}.log
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "     ${vmesslink3}" | tee -a /etc/xray/log-create-${user}.log
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "                    FORMAT OPENCLASH" | tee -a /etc/xray/log-create-${user}.log
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "     https://${domain}:81/vmess-$user.txt" | tee -a /etc/xray/log-create-${user}.log
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "Aktif Selama   : $masaaktif Hari" | tee -a /etc/xray/log-create-${user}.log
echo -e "Dibuat Pada    : $tnggl" | tee -a /etc/xray/log-create-${user}.log
echo -e "Berakhir Pada  : $expe" | tee -a /etc/xray/log-create-${user}.log
echo -e "${blue}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}" | tee -a /etc/xray/log-create-${user}.log
echo -e "" | tee -a /etc/xray/log-create-${user}.log
