#!/bin/bash
clear
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
domain=$(cat /etc/xray/domain)
PUB=$(cat /etc/slowdns/server.pub)
CITY=$(cat /etc/xray/city)
NS=$(cat /etc/xray/ns)
clear
until [[ $user =~ ^[a-zA-Z0-9_]+$ && ${CLIENT_EXISTS} == '0' ]]; do
  echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
  echo -e " \e[1;97;101m            ADD VLESS ACCOUNT           \e[0m"
  echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"

  read -p "User: " user
  CLIENT_EXISTS=$(grep -w $user /etc/xray/config.json | wc -l)

  if [[ ${CLIENT_EXISTS} == '1' ]]; then
    clear
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo -e " \e[1;97;101m            ADD VLESS ACCOUNT           \e[0m"
    echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    echo ""
    echo "A client with the specified name was already created, please choose another name."
    echo ""
    echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
    read -n 1 -s -r -p "Press [ Enter ] to back menu vless"
    vless
  fi
done
#cat >/usr/local/sbin/uuid <<EOF
#geo-project-anak-sumbawa
#EOF
#uuid=$(cat /usr/local/sbin/uuid)
uuid=$(cat /proc/sys/kernel/random/uuid)
echo ""
read -p "Expired (days): " masaaktif
read -p "Limit User (GB): " Quota
max=2
read -p "     Limit User (IP)  : " iplim
tgl=$(date -d "$masaaktif days" +"%d")
bln=$(date -d "$masaaktif days" +"%b")
thn=$(date -d "$masaaktif days" +"%Y")
expe="$tgl-$bln-$thn"
tgl2=$(date +"%d")
bln2=$(date +"%b")
thn2=$(date +"%Y")
tnggl="$tgl2-$bln2-$thn2"
exp=`date -d "$masaaktif days" +"%d-%b-%Y"`
sed -i '/#vless$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#vlessgrpc$/a\#& '"$user $exp"'\
},{"id": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
cat >/var/www/html/vless-$user.txt <<-END

---------------------
# Format Vless WS (CDN)
---------------------

- name: Vless-$user-WS (CDN)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
---------------------
# Format Vless WS (CDN) Non TLS
---------------------
- name: Vless-$user-WS (CDN) Non TLS
  server: ${domain}
  port: 80
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: false
  skip-cert-verify: false
  servername: ${domain}
  network: ws
  ws-opts:
    path: /vless
    headers:
      Host: ${domain}
  udp: true
---------------------
#  Format Vless gRPC (SNI)
---------------------
- name: Vless-$user-gRPC (SNI)
  server: ${domain}
  port: 443
  type: vless
  uuid: ${uuid}
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: ${domain}
  network: grpc
  grpc-opts:
  grpc-mode: gun
  grpc-service-name: vless-grpc
  udp: true

---------------------
# Link Vless Account
---------------------
Link TLS : vless://${uuid}@${domain}:443?path=/vless&security=tls&encryption=none&type=ws#${user}-WS-(CDN)-TLS
---------------------
Link none TLS : vless://${uuid}@${domain}:80?path=/vless&encryption=none&type=ws#${user}-WS-(CDN)-NTLS
---------------------
Link GRPC :vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}-(SNI)-GRPC
---------------------

END
vlesslink1="vless://${uuid}@${domain}:443?path=/vless&security=tls&host=${domain}&encryption=none&type=ws#${user}-WS-(CDN)-TLS"
vlesslink2="vless://${uuid}@${domain}:80?path=/vless&encryption=none&host=${domain}&type=ws#${user}-WS-(CDN)-NTLS"
vlesslink3="vless://${uuid}@${domain}:443?mode=gun&security=tls&encryption=none&type=grpc&serviceName=vless-grpc&sni=${domain}#${user}-(SNI)-GRPC"

systemctl restart xray
systemctl restart nginx
systemctl restart haproxy
service cron restart
systemctl restart xray
if [ ! -e /etc/vless ]; then
  mkdir -p /etc/vless
fi
if [ -z ${iplim} ]; then
  iplim="0"
fi
if [ -z ${Quota} ]; then
  Quota="0"
fi
c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))
if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/vless/${user}
  echo "${iplim}" >/etc/vless/${user}IP
fi
DATADB=$(cat /etc/vless/.vless.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/vless/.vless.db
fi
echo "### ${user} ${exp} ${uuid}" >>/etc/vless/.vless.db

clear
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e " \e[1;97;101m       SUCCES CREAT VLESS ACCOUNT       \e[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "Remarks     : ${user}" | tee -a /etc/xray/log-create-${user}.log
echo -e "Domain      : ${domain}" | tee -a /etc/xray/log-create-${user}.log
echo -e "User Quota  : ${Quota} GB" | tee -a /etc/xray/log-create-${user}.log
echo -e "port TLS    : 443" | tee -a /etc/xray/log-create-${user}.log
echo -e "Port DNS    : 443, 53 " | tee -a /etc/xray/log-create-${user}.log
echo -e "Port NTLS   : 80, 8080" | tee -a /etc/xray/log-create-${user}.log
echo -e "Port GRPC   : 443" | tee -a /etc/xray/log-create-${user}.log
echo -e "Port XRAY   : 443,80" | tee -a /etc/xray/log-create-${user}.log
echo -e "User ID     : ${uuid}" | tee -a /etc/xray/log-create-${user}.log
echo -e "AlterId     : 0" | tee -a /etc/xray/log-create-${user}.log
echo -e "Security    : auto" | tee -a /etc/xray/log-create-${user}.log
echo -e "Encryption  : none" | tee -a /etc/xray/log-create-${user}.log
echo -e "Path        : /vles - /multipath" | tee -a /etc/xray/log-create-${user}.log
echo -e "Path Dynamic : CF-XRAY:http://bug.com</" | tee -a /etc/xray/log-create-${user}.log
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "Link TLS   : ${vlesslink1}" | tee -a /etc/xray/log-create-${user}.log
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "Link NTLS  : ${vlesslink2}" | tee -a /etc/xray/log-create-${user}.log
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "Link GRPC  : ${vlesslink3}" | tee -a /etc/xray/log-create-${user}.log
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "Format OpenClash : https://${domain}:81/vless-$user.txt" | tee -a /etc/xray/log-create-${user}.log
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "Aktif Selama   : $masaaktif Hari" | tee -a /etc/xray/log-create-${user}.log
echo -e "Dibuat Pada    : $tnggl" | tee -a /etc/xray/log-create-${user}.log
echo -e "Berakhir Pada  : $expe" | tee -a /etc/xray/log-create-${user}.log
echo -e "\033[1;36m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m" | tee -a /etc/xray/log-create-${user}.log
echo -e "" | tee -a /etc/xray/log-create-${user}.log
