#!/bin/bash
# Getting
ISP=$(curl -s ipinfo.io/org | cut -d " " -f 2-10 )
CITY=$(curl -s ipinfo.io/city )
domain=$(cat /etc/xray/domain)
PUB=$(cat /etc/slowdns/server.pub)
NS=$(cat /etc/xray/ns.txt)
clear
read -p "   Username      : " user
read -p "   Password      : " Pass
read -p "   Expired (Days): " masaaktif
read -p "   Limit User (IP): " iplim
IP=$(curl -sS ipv4.icanhazip.com);
clear
useradd -e `date -d "$masaaktif days" +"%d-%B-%Y"` -s /bin/false -M $user
expi="$(chage -l $user | grep "Account expires" | awk -F": " '{print $2}')"
dbexp=$(date -d "$masaaktif days" +"%d-%B-%Y")
echo -e "$Pass\n$Pass\n"|passwd $user &> /dev/null
hariini=`date -d "0 days" +"%d-%B-%Y"`
expi=`date -d "$masaaktif days" +"%d-%B-%Y"`
if [[ ${c} != "0" ]]; then
  echo "${iplim}" >/etc/ssh/${user}
fi
DATADB=$(cat /etc/ssh/.ssh.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/ssh/.ssh.db
fi
echo "### ${user} ${dbexp}" >>/etc/ssh/.ssh.db
clear
cat >/var/www/html/ssh-$user.txt <<END

---------------------
Format SSH OVPN Account
---------------------
Username         : $user
Password         : $Pass
---------------------
Host XrayDNS : ${NS}
Pub Key          : ${PUB}
IP               : $IP
Host             : $domain
Port OpenSSH     : 443, 80, 22
Port UdpSSH      : 1-65535
Port Dropbear    : 443, 109
Port Dropbear WS : 443, 109
Port SSH WS      : 80, 8080
Port SSH SSL WS  : 443
Port SSL/TLS     : 443
Port OVPN WS SSL : 443
Port OVPN SSL    : 443
Port OVPN TCP    : 443, 1194
Port OVPN UDP    : 2200
BadVPN UDP       : 7100, 7300, 7300
---------------------
Payload WSS: GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf] 
---------------------
OpenVPN Link     : http://$domain:81
---------------------
Aktif Selama         : $masaaktif Hari
Dibuat Pada          : $hariini
Berakhir Pada        : $expi

END
clear
echo -e "\033[1;93m◇━━━━━━━━━━━━━━━━━◇\033[0m" | tee -a /etc/xray/log-createssh-${user}.log
echo -e " Informasi SSH & OpenVPN" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "\033[1;93m◇━━━━━━━━━━━━━━━━━◇\033[0m" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Username         : $user" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Password         : $Pass" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Created          : $hariini" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Expired       : $expi" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "IP               : $IP" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Host             : $domain" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Host Slowdns     : ${NS}" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Pub Key          : ${PUB}" | tee -a /etc/xray/log-createssh-${user}.log
#echo -e "Location         : $CITY" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Port OpenSSH     : 443, 80, 22" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Port DNS         : 443, 53 ,22 " | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Port SSH UDP     : 1-65535" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Port Dropbear    : 443, 109" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Port SSH WS      : 80, 8080" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Port SSH SSL WS  : 443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Port SSL/TLS     : 443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Port OVPN WS SSL : 443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Port OVPN SSL    : 443" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Port OVPN TCP    : 443, 1194" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Port OVPN UDP    : 2200" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "BadVPN UDP       : 7100, 7300, 7300" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "\033[1;93m◇━━━━━━━━━━━━━━━━━◇\033[0m" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Payload WSS      : GET wss://BUG.COM/ HTTP/1.1[crlf]Host: $domain[crlf]Upgrade: websocket[crlf][crlf]" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "\033[1;93m◇━━━━━━━━━━━━━━━━━◇\033[0m" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "OVPN Download    : https://$domain:81/" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "\033[1;93m◇━━━━━━━━━━━━━━━━━◇\033[0m" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "Save Link Account: https://$domain:81/ssh-$user.txt" | tee -a /etc/xray/log-createssh-${user}.log
echo -e "\033[1;93m◇━━━━━━━━━━━━━━━━━◇\033[0m" | tee -a /etc/xray/log-createssh-${user}.log
