#!/bin/bash
clear
cyan="\033[1;36m"
NC='\033[0m'
echo""
echo -e " ${cyan}=======================================${NC}"
echo -e "         ⚡ DOMAIN GRATIS \e[1;92m⚡$NC"
echo -e " ${cyan}=======================================${NC}"
read -rp "   ⚡ Masukkan IP VPS  : " ipinput
echo -e " ${cyan}=======================================${NC}"
echo " "
echo "         Data telah diterima dan akan segera diprogres"
DOMAIN=mapin.my.id
sub=$(</dev/urandom tr -dc a-z0-9 | head -c6)
SUB_DOMAIN=${sub}.mapin.my.id
CF_ID=ambebalong@gmail.com
CF_KEY=5fae9fcb9c193ce65de4b57689a94938b708e
set -euo pipefail
IP=$ipinput
echo "Updating DNS for ${SUB_DOMAIN}..."
sleep 3
ZONE=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones?name=${DOMAIN}&status=active" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" | jq -r .result[0].id)

RECORD=$(curl -sLX GET "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records?name=${SUB_DOMAIN}" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" | jq -r .result[0].id)

if [[ "${#RECORD}" -le 10 ]]; then
     RECORD=$(curl -sLX POST "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" \
     --data '{"type":"A","name":"'${SUB_DOMAIN}'","content":"'${IP}'","proxied":false}' | jq -r .result.id)
fi

RESULT=$(curl -sLX PUT "https://api.cloudflare.com/client/v4/zones/${ZONE}/dns_records/${RECORD}" \
     -H "X-Auth-Email: ${CF_ID}" \
     -H "X-Auth-Key: ${CF_KEY}" \
     -H "Content-Type: application/json" \
     --data '{"type":"A","name":"'${SUB_DOMAIN}'","content":"'${IP}'","proxied":false}')

clear
echo -e " ${cyan}=======================================${NC}"
echo -e " ⚡ DOMAIN TELAH BERHASIL DIPOINTING \e[1;92m⚡$NC"
echo -e " ${cyan}=======================================${NC}"
echo ""
echo "  ⚡ Domain Pointing : [ $SUB_DOMAIN ]"
echo "  ⚡ IP VPS Pointing : [ $ipinput ]"
echo " "
echo " Jangan lupa dicatat dan gunakan saat instalasi VPS anda"
echo "   TERIMA KASIH TELAH MENGGUNAKAN SCRIPT PREMIUM INI"
echo -e " ${cyan}=======================================${NC}"
echo -e "     ⚡ POWERED BY SCRIPT PREMIUM \e[1;92m⚡$NC"
echo -e " ${cyan}=======================================${NC}"
echo ""
echo -ne "[ WARNING ] Apakah anda ingin kembali ke menu ? (y/n)? "
read answer
if [ "$answer" == "${answer#[Yy]}" ] ;then
exit 0
else
menu
fi
