#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
NC='\033[0m'
OR='\033[1;93m'
grenbo="\e[92;1m"

# System commands status
city=$(cat /etc/xray/city)
dat=$(date +"%d-%B-%Y")
isp=$(cat /etc/xray/isp)
PUB=$(cat /etc/slowdns/server.pub)
KEY=$(cat /etc/slowdns/server.key)
DNS=$(cat /etc/xray/ns.txt)
domain=$(cat /etc/xray/domain)

bot_tele() {
    clear
    BOTTTT=$(systemctl status geo | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
    if [[ $BOTTTT == "running" ]]; then
        STATBOT="${grenbo} Online${NC}"
    else
        STATBOT="${RED} Offline${NC}"
    fi
    uuid=$(tr </dev/urandom -dc a-z | head -c15)

    echo -e "  ${OR}===========================${NC}"
    echo -e "  \e[1;92m BOT SIMPLE geo TELEGRAM"
    echo -e "  ${OR}===========================${NC}"
    echo ""
    echo -e "  YOUR BOT STATUS $STATBOT    "
    echo -e "  Telegram Bot Setup menu"
    echo -e "  Make Vpn In The Telegram Bot"
    echo -e "  Short Tutorials :"
    echo -e "  Get This Value From @BotFather, Required"
    echo -e "  Take Your ID at @MissRose_bot,cmd (/id)"
    echo -e "  ${OR}===========================${NC}"
    read -e -p "  Input your Bot Token : " bottoken
    read -e -p "  Input your Id Telegram : " idtelegram
    rm -rf /home/geo/database.db >/dev/null 2>&1

    cat >/home/geo/var.txt <<EOF
BOT_TOKEN="$bottoken"
ADMIN="$idtelegram"
DOMAIN="$domain"
PUB="$PUB"
DNS="$DNS"
SESSIONS="$uuid"
USER1="empty1"
USER2="empty2"
USER3="empty3"
USER4="empty4"
USER5="empty5"
USER6="empty6"
USER7="empty7"
USER8="empty8"
USER9="empty9"
USER10="empty0"
EOF

    systemctl daemon-reload
    systemctl stop geo
    systemctl enable geo
    systemctl start geo
    systemctl restart geo
    clear
    fun_bar() {
CMD[0]="$1"
CMD[1]="$2"
(
[[ -e $HOME/fim ]] && rm $HOME/fim
${CMD[0]} -y >/dev/null 2>&1
${CMD[1]} -y >/dev/null 2>&1
touch $HOME/fim
) >/dev/null 2>&1 &
tput civis
echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
while true; do
for ((i = 0; i < 18; i++)); do
echo -ne "\033[0;32m#"
sleep 0.1s
done
[[ -e $HOME/fim ]] && rm $HOME/fim && break
echo -e "\033[0;33m]"
sleep 1s
tput cuu1
tput dl1
echo -ne "  \033[0;33mPlease Wait Loading \033[1;37m- \033[0;33m["
done
echo -e "\033[0;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
    }
    sssssss() {
        sleep 5
    }
    sssssssss() {
        sleep 5
    }
    ssssssssssss() {
        sleep 2
    }

    echo -e "  ${OR}=======================${NC}"
    echo -e " BOT SIMPLE geo TELEGRAM "
    echo -e "  ${OR}=======================${NC}"
    echo -e ""
    echo -e "Setting up Telegram BOT"
    fun_bar 'sssssss'
    echo -e "Input Data API TOKEN"
    fun_bar 'sssssssss'
    echo -e "Input your ID"
    fun_bar 'ssssssssssss'
    echo -e ""
    echo -e ""
    clear
    BOTTSSSTT=$(systemctl status geo | grep active | awk '{print $3}' | sed 's/(//g' | sed 's/)//g')
    if [[ $BOTTSSSTT == "running" ]]; then
        BOTBOTTTTSUDADHTTT="${grenbo} Online${NC}"
    else
        BOTBOTTTTSUDADHTTT="${RED} Offline${NC}"
    fi
    echo -e " ${OR}=======================${NC}"
    echo -e " YOUR BOT STATUS $BOTBOTTTTSUDADHTTT"
    echo -e " ${OR}=======================${NC}"
    echo -e "  You can start the bot with the command"
    echo -e "     (/menu Atau .menu) On your BOT"
    echo -e "   then you can add several admins / id"
    echo -e ""
}
add_bot() {
    clear
    echo -e " ${OR}=======================${NC}"
    echo -e "  \e[0m\e[1;77mAdmin Simple BOT Tele \e[1;92m\e[0m\n"
    echo -e " ${OR}=======================${NC}"
    source '/home/geo/var.txt'
    echo "     USER ID TELEGRAM"
    echo "     1. $USER1"
    echo "     2. $USER2"
    echo "     3. $USER3"
    echo "     4. $USER4"
    echo "     5. $USER5"
    echo "     6. $USER6"
    echo "     7. $USER7"
    echo "     8. $USER8"
    echo "     9. $USER9"
    echo "     10. $USER10"
    botadd1() {
        read -rp "  Input ur admin 1 : " -e admin1
        sed -i "s/$USER1/$admin1/g" /home/geo/var.txt
        sed -i "s/$SESSIONS/$uuid/g" /home/geo/var.txt
        rm -rf /home/geo/database.db
        systemctl daemon-reload
        systemctl stop geo
        systemctl enable geo
        systemctl start geo
        systemctl restart geo
        echo "Successfull added admin bot"
        read -n 1 -s -r -p "Press any key to back on menu"
        m-bot
        read -n 1 -s -r -p "Press any key to back on menu"
        m-bot
    }
    botadd2() {
        read -rp "  Input ur admin 2 : " -e admin2
        sed -i "s/$USER2/$admin2/g" /home/geo/var.txt
        sed -i "s/$SESSIONS/$uuid/g" /home/geo/var.txt
        rm -rf /home/geo/database.db
        systemctl daemon-reload
        systemctl stop geo
        systemctl enable geo
        systemctl start geo
        systemctl restart geo
        echo "Successfull added admin bot"
        read -n 1 -s -r -p "Press any key to back on menu"
        m-bot
    }
    botadd3() {
        read -rp "  Input ur admin 3 : " -e admin3
        sed -i "s/$USER3/$admin3/g" /home/geo/var.txt
        sed -i "s/$SESSIONS/$uuid/g" /home/geo/var.txt
        rm -rf /home/geo/database.db
        systemctl daemon-reload
        systemctl stop geo
        systemctl enable geo
        systemctl start geo
        systemctl restart geo
        echo "Successfull added admin bot"
        read -n 1 -s -r -p "Press any key to back on menu"
        m-bot
    }
    botadd4() {
        read -rp "  Input ur admin 4 : " -e admin4
        sed -i "s/$USER4/$admin4/g" /home/geo/var.txt
        sed -i "s/$SESSIONS/$uuid/g" /home/geo/var.txt
        rm -rf /home/geo/database.db
        systemctl daemon-reload
        systemctl stop geo
        systemctl enable geo
        systemctl start geo
        systemctl restart geo
        echo "Successfull added admin bot"
        read -n 1 -s -r -p "Press any key to back on menu"
        m-bot
    }
    botadd5() {
        read -rp "  Input ur admin 5 : " -e admin5
        sed -i "s/$USER5/$admin5/g" /home/geo/var.txt
        sed -i "s/$SESSIONS/$uuid/g" /home/geo/var.txt
        rm -rf /home/geo/database.db
        systemctl daemon-reload
        systemctl stop geo
        systemctl enable geo
        systemctl start geo
        systemctl restart geo
        echo "Successfull added admin bot"
        read -n 1 -s -r -p "Press any key to back on menu"
        m-bot
    }
    botadd6() {
        read -rp "  Input ur admin 6 : " -e admin6
        sed -i "s/$USER6/$admin6/g" /home/geo/var.txt
        sed -i "s/$SESSIONS/$uuid/g" /home/geo/var.txt
        rm -rf /home/geo/database.db
        systemctl daemon-reload
        systemctl stop geo
        systemctl enable geo
        systemctl start geo
        systemctl restart geo
        echo "Successfull added admin bot"
        read -n 1 -s -r -p "Press any key to back on menu"
        m-bot
    }
    botadd7() {
        read -rp "  Input ur admin 7 : " -e admin7
        sed -i "s/$USER7/$admin7/g" /home/geo/var.txt
        sed -i "s/$SESSIONS/$uuid/g" /home/geo/var.txt
        rm -rf /home/geo/database.db
        systemctl daemon-reload
        systemctl stop geo
        systemctl enable geo
        systemctl start geo
        systemctl restart geo
        echo "Successfull added admin bot"
        read -n 1 -s -r -p "Press any key to back on menu"
        m-bot
    }
    botadd8() {
        read -rp "  Input ur admin 8 : " -e admin8
        sed -i "s/$USER8/$admin8/g" /home/geo/var.txt
        sed -i "s/$SESSIONS/$uuid/g" /home/geo/var.txt
        rm -rf /home/geo/database.db
        systemctl daemon-reload
        systemctl stop geo
        systemctl enable geo
        systemctl start geo
        systemctl restart geo
        echo "Successfull added admin bot"
        read -n 1 -s -r -p "Press any key to back on menu"
        m-bot
    }
    botadd9() {
        read -rp "  Input ur admin 9 : " -e admin9
        sed -i "s/$USER9/$admin9/g" /home/geo/var.txt
        sed -i "s/$SESSIONS/$uuid/g" /home/geo/var.txt
        rm -rf /home/geo/database.db
        systemctl daemon-reload
        systemctl stop geo
        systemctl enable geo
        systemctl start geo
        systemctl restart geo
        echo "Successfull added admin bot"
        read -n 1 -s -r -p "Press any key to back on menu"
        m-bot
    }
    botadd10() {
        read -rp "  Input ur admin 10 : " -e admin10
        sed -i "s/$USER10/$admin10/g" /home/geo/var.txt
        sed -i "s/$SESSIONS/$uuid/g" /home/geo/var.txt
        rm -rf /home/geo/database.db
        systemctl daemon-reload
        systemctl stop geo
        systemctl enable geo
        systemctl start geo
        systemctl restart geo
        echo "Successfull added admin bot"
        read -n 1 -s -r -p "Press any key to back on menu"
        m-bot
    }
    read -p "  Select From Options [ 1 - 10 ] : " menubot
    case $menubot in
    1) botadd1 ;;
    2) botadd2 ;;
    3) botadd3 ;;
    4) botadd4 ;;
    5) botadd5 ;;
    6) botadd6 ;;
    7) botadd7 ;;
    8) botadd8 ;;
    9) botadd9 ;;
    10) botadd10 ;;

    *)
        exit 0
        ;;
    esac
}
clear
echo -e
echo -e " ${OR}=======================${NC}"
echo -e "        MANAGER BOT"
echo -e " ${OR}=======================${NC}"
echo -e "\033[1;93m ${grenbo}1.${NC} \033[0;36mSetup Bot Admin Telegram${NC}"
echo -e "\033[1;93m ${grenbo}2.${NC} \033[0;36mAdded Bot Admin Telegram${NC}"
echo -e "\033[1;93m ${grenbo}3.${NC} \033[0;36mRestart/Reboot server${NC}"
echo -e "\033[1;93m ${grenbo}x.${NC} \033[0;36mExit system settings${NC}"
echo -e " ${OR}=======================${NC}"
echo -e ""
read -p "  Select From Options [ 1 - 3 ] : " menu
case $menu in
1) bot_tele ;;
2) add_bot ;;
3) reboot ;;
*)
    exit 0
    ;;
esac
