#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	Geo Project
# //	Dscription: Xray Menu Management
# //	email: admin@geolstore.net
# //  telegram: https://t.me/tau_samawa
# //====================================================

# // Root Checking
if [ "${EUID}" -ne 0 ]; then
		echo -e "${EROR} Please Run This Script As Root User !"
		exit 1
fi

# // Export Color & Information
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHT='\033[0;37m'
export NC='\033[0m'
OR='\033[0;34m'
Lred='\e[91m'
LLgreen='\e[92m'
Lyellow='\e[93m'
yellow="\033[1;33m"
green="\e[92;1m"
yellow="\033[1;33m"
cyan="\033[1;36m"

# // Export Banner Status Information
export EROR="[${RED} ERROR ${NC}]"
export INFO="[${YELLOW} INFO ${NC}]"
export OKEY="[${GREEN} OKEY ${NC}]"
export PENDING="[${YELLOW} PENDING ${NC}]"
export SEND="[${YELLOW} SEND ${NC}]"
export RECEIVE="[${YELLOW} RECEIVE ${NC}]"

# // Export Align
export BOLD="\e[1m"
export WARNING="${RED}\e[5m"
export UNDERLINE="\e[4m"

# // Exporting URL Host
export Server_URLL="raw.githubusercontent.com/jaka1m/perizinan/main"
export Server_Port="443"
export Server_IP="underfined"
export Script_Mode="Stable"
export Auther="geovpn"
MYIP=$(curl -sS ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)

# // Exporting IP Address
export IP=$( curl -sS ipinfo.io/ip )

# // Exporting Network Interface
export NETWORK_IFACE="$(ip route show to default | awk '{print $5}')"

# // Validate Result ( 1 )
touch /etc/${Auther}/license.key
export Your_License_Key="$( cat /etc/${Auther}/license.key | awk '{print $1}' )"
export Validated_Your_License_Key_With_Server="$( curl -s https://${Server_URLL}/registered.txt | grep -w $Your_License_Key | head -n1 | cut -d ' ' -f 1 )"
if [[ "$Validated_Your_License_Key_With_Server" == "$Your_License_Key" ]]; then
    validated='true'
else
    echo -e "${EROR} License Key Not Valid"
    exit 1
fi

# // Checking Script Expired
exp=$( curl -s https://${Server_URLL}/registered.txt | grep -w $Your_License_Key | cut -d ' ' -f 4 )
now=`date -d "0 days" +"%Y-%m-%d"`
expired_date=$(date -d "$exp" +%s)
now_date=$(date -d "$now" +%s)
sisa_hari=$(( ($expired_date - $now_date) / 86400 ))
if [[ $sisa_hari -lt 0 ]]; then
    echo $sisa_hari > /etc/${Auther}/license-remaining-active-days.db
    echo -e "${EROR} Your License Key Expired ( $sisa_hari Days )"
    exit 1
else
    echo $sisa_hari > /etc/${Auther}/license-remaining-active-days.db
fi
clear
function convert() {
    local -i bytes=$1
    if [[ $bytes -lt 1024 ]]; then
        echo "${bytes}B"
    elif [[ $bytes -lt 1048576 ]]; then
        echo "$(((bytes + 1023) / 1024))KB"
    elif [[ $bytes -lt 1073741824 ]]; then
        echo "$(((bytes + 1048575) / 1048576))MB"
    else
        echo "$(((bytes + 1073741823) / 1073741824))GB"
    fi
}

clear
chngelimit() {
    clear
    echo -e "  ${OR}───────────────────────────────────────${NC}"
    printf "\e[1;92m    ⚜⚜ \e[0m\e[1;77m Chnge Xray/Vless Account \e[1;92m⚜⚜\e[0m\n"
    echo -e "  ${OR}───────────────────────────────────────${NC}"
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vless/.vless.db")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        echo ""
        echo "       No customer name available"
        echo ""
        exit 0
    fi
    echo ""
    echo "     NO  USERNAME     EXPIRED"
    echo "     ------------------------"
    grep -E "^### " "/etc/vless/.vless.db" | cut -d ' ' -f 2-3 | column -t | nl -s ') '
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp "Select one client [1]: " CLIENT_NUMBER
        else
            echo ""
            until [[ $CLIENT_NUMBER =~ ^[0-9]+$ ]]; do
                read -rp "     Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            done
            user=$(grep -E "^### " "/etc/vless/.vless.db" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
            clear
            until [[ $Quota =~ ^[0-9]+$ ]]; do
                read -p "Limit User (GB): " Quota
            done
            until [[ $iplim =~ ^[0-9]+$ ]]; do
                read -p "Limit User (IP): " iplim
            done

            if [ ! -e /etc/vless ]; then
                mkdir -p /etc/vless
            fi
            if [ -z ${iplim} ]; then
                iplim="0"
            fi
            if [ -z ${Quota} ]; then
                Quota="0"
            fi
            c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
            d=$((${c} * 1024 * 1024 * 1024))
            if [[ ${c} != "0" ]]; then
                echo "${d}" >/etc/vless/${user}
                echo "${iplim}" >/etc/vless/${user}IP
            fi
            clear
            echo "-----------------------------------------------"
            echo -e "Chnge Vless Account Username ${green}$user${NC} Successfully"
            echo -e "limit Quota $Quota GB limit Login IP $iplim Device"
            echo "-----------------------------------------------"
            echo ""
            exit
        fi
    done

}
log-vless() {
    clear
    echo -e "  ${OR}───────────────────────────────────────${NC}"
    printf "\e[1;92m    ⚜⚜ \e[0m\e[1;77m log Xray/Vless Account \e[1;92m⚜⚜\e[0m\n"
    echo -e "  ${OR}───────────────────────────────────────${NC}"
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vless/.vless.db")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        echo ""
        echo "       No customer name available"
        echo ""
        exit 0
    fi
    echo ""
    echo "     NO  USERNAME     EXPIRED"
    echo "     ------------------------"
    grep -E "^### " "/etc/vless/.vless.db" | cut -d ' ' -f 2-3 | column -t | nl -s ') '
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp "Select one client [1]: " CLIENT_NUMBER
        else
            echo ""
            until [[ $CLIENT_NUMBER =~ ^[0-9]+$ ]]; do
                read -rp "     Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            done
            user=$(grep -E "^### " "/etc/vless/.vless.db" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
            clear
            cat /var/log/xray/access.log | grep $user
            exit
        fi
    done
}
detail-vless() {
    clear
    echo -e "  ${OR}───────────────────────────────────────${NC}"
    printf "\e[1;92m    ⚜⚜ \e[0m\e[1;77m Detail Xray/Vless Account \e[1;92m⚜⚜\e[0m\n"
    echo -e "  ${OR}───────────────────────────────────────${NC}"
    NUMBER_OF_CLIENTS=$(grep -c -E "^### " "/etc/vless/.vless.db")
    if [[ ${NUMBER_OF_CLIENTS} == '0' ]]; then
        echo ""
        echo "       No customer name available"
        echo ""
        exit 0
    fi
    echo ""
    echo "     NO  USERNAME     EXPIRED"
    echo "     ------------------------"
    grep -E "^### " "/etc/vless/.vless.db" | cut -d ' ' -f 2-3 | column -t | nl -s ') '
    until [[ ${CLIENT_NUMBER} -ge 1 && ${CLIENT_NUMBER} -le ${NUMBER_OF_CLIENTS} ]]; do
        if [[ ${CLIENT_NUMBER} == '1' ]]; then
            read -rp "Select one client [1]: " CLIENT_NUMBER
        else
            echo ""
            until [[ $CLIENT_NUMBER =~ ^[0-9]+$ ]]; do
                read -rp "     Select one client [1-${NUMBER_OF_CLIENTS}]: " CLIENT_NUMBER
            done
            user=$(grep -E "^### " "/etc/vless/.vless.db" | cut -d ' ' -f 2 | sed -n "${CLIENT_NUMBER}"p)
            clear
            cat /etc/xray/log-create-${user}.log
            exit
        fi
    done

}

mem-vless() {
    clear
    echo -e "  ${cyan}=======================================${NC}"
    printf "\e[1;92m    ⚜⚜ \e[0m\e[1;77m Member Xray/Vless Account \e[1;92m⚜⚜\e[0m\n"
    echo -e "  ${cyan}=======================================${NC}"
    echo ""
    echo -e "   username     day.left   ip      quota"
    echo -e "  ${cyan}=======================================${NC}"
    data=($(cat /etc/vless/.vless.db | grep '^###' | cut -d ' ' -f 2 | sort | uniq))
    now=$(date +"%Y-%m-%d")
    for user in "${data[@]}"; do
        exp=$(grep -w "^### $user" "/etc/vless/.vless.db" | cut -d ' ' -f 3 | sort | uniq)
        d1=$(date -d "$exp" +%s)
        d2=$(date -d "$now" +%s)
        dayleft=$((($d1 - $d2) / 86400))
        if [[ -e /etc/limit/vless/${user} ]]; then
            byt=$(cat /etc/limit/vless/${user})
            gb=$(convert ${byt})
        else
            gb=""
        fi
        res=$(cat /etc/vless/${user}IP)
        if [[ "$dayleft" -le "500" ]]; then
            printf "\e[1m  %-13s %-7s %-8s %2s\n\e[22m" " $user" "| $dayleft" "|  $res" "|  $gb"
            printf "  %-13s %-7s %-8s %2s\n" "======================================="

        fi
    done
    echo ""

}
clear
green="\e[92;1m"
NC='\033[0m'
echo -e "\033[0;34m┌───────────────────────────────┐\033[0m"
echo -e "\033[0;34m│$NC$L1\033[41m       MENU MANAGER VLESS      $NC\033[0;34m│$NC"
echo -e "\033[0;34m└───────────────────────────────┘\033[0m"
echo -e "\033[0;34m┌───────────────────────────────┐\033[0m"
echo -e "\033[0;34m│$NC [${GREEN}01${NC}]$L1 Creating a Vless Account${NC}"
echo -e "\033[0;34m│$NC [${GREEN}02${NC}]$L1 Delete Vless Account${NC}"
echo -e "\033[0;34m│$NC [${GREEN}03${NC}]$L1 Renew Vless Account${NC}"
echo -e "\033[0;34m│$NC [${GREEN}04${NC}]$L1 Check Vless login Account${NC}"
echo -e "\033[0;34m│$NC [${GREEN}05${NC}]$L1 Member Vless Account${NC}"
echo -e "\033[0;34m│$NC [${GREEN}06${NC}]$L1 Chnge Vless limit Account${NC}"
echo -e "\033[0;34m│$NC [${GREEN}07${NC}]$L1 Log Vless login Account${NC}"
echo -e "\033[0;34m│$NC [${GREEN}08${NC}]$L1 Detail Vless Account${NC}"
echo -e "\033[0;34m│$NC [${GREEN}09${NC}]$L1 Trial Vless Account${NC}"
echo -e "\033[0;34m│$NC "
echo -e "\033[0;34m│$NC [${GREEN}00${NC}]$L1 Back to Menu \033[1;32m<\033[1;33m<\033[1;31m<\033[1;31m$NC \E[0m\033[0;34m $NC"
echo -e "\033[0;34m└───────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 9 ] : " menu
case $menu in
1 | 01)
    addvless
    ;;
2 | 02)
    delvless
    ;;
3 | 03)
    renewvless
    ;;
4 | 04)
    cekvless
    ;;
5 | 05)
    mem-vless
    ;;
6 | 06)
    chngelimit
    ;;
7 | 07)
    log-vless
    ;;
8 | 08)
    detail-vless
    ;;
9 | 09)
    trialvless
        ;;
0 | 00)
clear
menu
       ;;
*)
echo -e ""
m-vless
;;
esac
