#!/bin/bash
# //====================================================
# //	System Request:Debian 9+/Ubuntu 18.04+/20+
# //	Author:	Geo Project
# //	Dscription: Xray Menu Management
# //	email: admin@geolstore.net
# //  telegram: https://t.me/tau_samawa
# //====================================================

# // Root Checking
if [ "${EUID}" -ne 0 ]; then
		echo -e "${EROR} Please Run This Script As Root User !"
		exit 1
fi

# // Export Color & Information
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHT='\033[0;37m'
export NC='\033[0m'
OR='\033[1;93m'
Lred='\e[91m'
LLgreen='\e[92m'
Lyellow='\e[93m'
yellow="\033[1;33m"
green="\e[92;1m"
yellow="\033[1;33m"
cyan="\033[1;36m"

# // Export Banner Status Information
export EROR="[${RED} ERROR ${NC}]"
export INFO="[${YELLOW} INFO ${NC}]"
export OKEY="[${GREEN} OKEY ${NC}]"
export PENDING="[${YELLOW} PENDING ${NC}]"
export SEND="[${YELLOW} SEND ${NC}]"
export RECEIVE="[${YELLOW} RECEIVE ${NC}]"

# // Export Align
export BOLD="\e[1m"
export WARNING="${RED}\e[5m"
export UNDERLINE="\e[4m"

# // Exporting URL Host
export Server_URLL="raw.githubusercontent.com/jaka1m/perizinan/main"
export Server_Port="443"
export Server_IP="underfined"
export Script_Mode="Stable"
export Auther="geovpn"
MYIP=$(curl -sS ipv4.icanhazip.com)
domain=$(cat /etc/xray/domain)

# // Exporting IP Address
export IP=$( curl -sS ipinfo.io/ip )

# // Exporting Network Interface
export NETWORK_IFACE="$(ip route show to default | awk '{print $5}')"

# // Validate Result ( 1 )
touch /etc/${Auther}/license.key
export Your_License_Key="$( cat /etc/${Auther}/license.key | awk '{print $1}' )"
export Validated_Your_License_Key_With_Server="$( curl -s https://${Server_URLL}/registered.txt | grep -w $Your_License_Key | head -n1 | cut -d ' ' -f 1 )"
if [[ "$Validated_Your_License_Key_With_Server" == "$Your_License_Key" ]]; then
    validated='true'
else
    echo -e "${EROR} License Key Not Valid"
    exit 1
fi

# // Checking Script Expired
exp=$( curl -s https://${Server_URLL}/registered.txt | grep -w $Your_License_Key | cut -d ' ' -f 4 )
now=`date -d "0 days" +"%Y-%m-%d"`
expired_date=$(date -d "$exp" +%s)
now_date=$(date -d "$now" +%s)
sisa_hari=$(( ($expired_date - $now_date) / 86400 ))
if [[ $sisa_hari -lt 0 ]]; then
    echo $sisa_hari > /etc/${Auther}/license-remaining-active-days.db
    echo -e "${EROR} Your License Key Expired ( $sisa_hari Days )"
    exit 1
else
    echo $sisa_hari > /etc/${Auther}/license-remaining-active-days.db
fi
clear
echo -e "  ${OR}──────────────────────────────────────${NC}"
printf "\e[1;92m    ⚜⚜  \e[0m\e[1;77m Trial Xray/Trojan Account \e[1;92m⚜⚜  \e[0m\n"
echo -e "  ${OR}──────────────────────────────────────${NC}"
echo ""
read -p "  Expired (Minutes): " timer
until [[ $Quota =~ ^[0-9]+$ ]]; do
  read -p "   Limit User (GB): " Quota
done
until [[ $iplim =~ ^[0-9]+$ ]]; do
  read -p "   Limit User (IP): " iplim
done
read -p "   Bug Host (bug): " BUG
user=Trial_$(tr </dev/urandom -dc X-Z0-9 | head -c4)
uuid=$(cat /proc/sys/kernel/random/uuid)
exp=$(date -d "1 days" +"%Y-%m-%d")
sed -i '/#trojanws$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
sed -i '/#trojangrpc$/a\#! '"$user $exp"'\
},{"password": "'""$uuid""'","email": "'""$user""'"' /etc/xray/config.json
cat >/var/www/html/trojan-$user.txt <<-END

---------------------
# Format Trojan GO/WS (CDN)
---------------------

- name: Trojan-$user-GO/WS (CDN)
  server: ${domain}
  port: 443
  type: trojan
  password: ${uuid}
  network: ws
  sni: ${domain}
  skip-cert-verify: true
  udp: true
  ws-opts:
    path: /trojan-ws
    headers:
        Host: ${domain}
---------------------
# Format Trojan gRPC
---------------------

- name: Trojan-$user-gRPC (SNI)
  type: trojan
  server: ${domain}
  port: 443
  password: ${uuid}
  udp: true
  sni: ${domain}
  skip-cert-verify: true
  network: grpc
  grpc-opts:
    grpc-service-name: trojan-grpc

---------------------
 Link Trojan Account
---------------------
Link WS : trojan://${uuid}@${domain}:443?path=%2Fwhatever%2Ftrojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#Trojan-$user-GO%2BWS
---------------------
Link GRPC : trojan://${uuid}@${domain}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#Trojan-$user-GRPC
---------------------

END
systemctl restart xray
trojanlink="trojan://${uuid}@${BUG}:443?path=/trojan-ws&security=tls&host=${domain}&type=ws&sni=${domain}#Trojan-$user-GO%2BWS"
trojanlink1="trojan://${uuid}@${BUG}:443?mode=gun&security=tls&type=grpc&serviceName=trojan-grpc&sni=${domain}#Trojan-$user-GRPC"
trojanlink2="trojan://${uuid}@${BUG}:80?path=/trojan-ws&security=none&host=${domain}&type=ws&sni=${domain}#Trojan-$user-NON%2BWS"
systemctl restart xray
tmux new-session -d -s $user "trial trialtr $user $timer"
if [ ! -e /etc/trojan ]; then
  mkdir -p /etc/trojan
fi

if [ -z ${Quota} ]; then
  Quota="0"
fi
if [ -z ${iplim} ]; then
  iplim="0"
fi
c=$(echo "${Quota}" | sed 's/[^0-9]*//g')
d=$((${c} * 1024 * 1024 * 1024))

if [[ ${c} != "0" ]]; then
  echo "${d}" >/etc/trojan/${user}
  echo "${iplim}" >/etc/trojan/${user}IP
fi
DATADB=$(cat /etc/trojan/.trojan.db | grep "^###" | grep -w "${user}" | awk '{print $2}')
if [[ "${DATADB}" != '' ]]; then
  sed -i "/\b${user}\b/d" /etc/trojan/.trojan.db
fi
echo "### ${user} ${exp} ${uuid}" >>/etc/trojan/.trojan.db
clear
echo -e "
\033[0;34m====================\033[0m
\e[92;1m Xray/Trojan Account    \E[0m
\033[0;34m====================\033[0m
Remarks     : ${user}
Host Server : ${domain}
User Quota  : ${Quota} GB
User IP     : ${iplim} IP
port TLS    : 443
port NTLS   : 80
ServiceName : trojan-grpc
Path        : /Multi/trojan-ws
\033[0;34m====================\033[0m
Link TLS    : ${trojanlink}
\033[0;34m====================\033[0m
Link NTLS  : ${trojanlink2}
\033[0;34m====================\033[0m
Link GRPC  : ${trojanlink1}
\033[0;34m====================\033[0m
Format OpenClash : https://${domain}:81/trojan-$user.txt
\033[0;34m====================\033[0m
Expired On : $timer Minutes
\033[0;34m====================\033[0m
" | tee -a /etc/xray/log-create-${user}.log
echo "" 
read -n 1 -s -r -p "Press any key to back on menu"
m-trojan
